### PR TITLE
Prep for Google Fonts submission

### PR DESCRIPTION
**Pull request by solmatas**
- Adjustments to source glyphs file
- Completed documentation
- Extra images
- Scripted post-export adjustments

### CODE REVIEW

**Review by kkaempf — CHANGES_REQUESTED** [review]
The copyright statement needs to be clarified

**Comment by solmatas** [comment]
> The copyright statement needs to be clarified

I'm glad you spotted that repo name.

About the copyright, Google Fonts is quite restrictive.  

The short string you're hoping for fails this required check:

https://github.com/fonttools/fontbakery/blob/92400895550624a1b8fcef55297fc424b36fdce3/Lib/fontbakery/checks/googlefonts/license.py#L111

The regex pattern is here:

https://github.com/fonttools/fontbakery/blob/92400895550624a1b8fcef55297fc424b36fdce3/Lib/fontbakery/checks/googlefonts/constants.py#L25

"copyright \d{4}(-\d{4})?(,\s*\d{4}(-\d{4})?)*,? (the .* project authors \([^\@]*\)|google llc. all rights reserved)"

How do you feel about this string instead?  Note that I’ve removed LLC because they’re expecting the family name, not the organization name.

**Copyright 2024 The SUSE Project Authors (https://github.com/SUSE/suse-font)**

**Comment by andyfitz-suse** [comment]
Will take your advice here Sol,  thanks.  I'll comment on the name exception issue with Google :)

**Comment by solmatas** [comment]
Great! Once you approve this PR, I’ll try out the make customize steps, it looks at the URLs.

https://github.com/SUSE/suse-font/pull/2

**Pull request merged**
